name: samdul
services:
  blog:
    build: ./docker/httpd
    ports:
      - 80
    volumes:
      - ./docker/mangG907.github.io:/usr/local/apache2/htdocs/
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=80


  load_balancer:
    image: nginxproxy/nginx-proxy
    #container_name: blog-lb
    #build: ./docker/nginx
    ports:
      - 8949:80
    depends_on:
      - blog
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    #links:
     # - blog
